# Librairies
```{r}
library(DBI)
library(RMariaDB)
library(jsonlite)
library(readxl)
library(rvest)
library(pdftools)
library(progress)
library(tidyverse)
library(shiny)
```

# Connexion à la BDD mysql
```{r}
db_user <- '384054_admin'
db_password <- 'qZ9XcWesVVq9tiY'
db_name <- 'tp-groupe-r_airport'
db_host <- 'mysql-tp-groupe-r.alwaysdata.net'
db_port <- 3306

# Connexion à la base de données
mydb <- dbConnect(MariaDB(), user = db_user, password = db_password,
                  dbname = db_name, host = db_host, port = db_port)
```

# Insertion des données
```{r}
json_data <- fromJSON("data/airlines.json")
dbWriteTable(mydb, "airlines", json_data, row.names = FALSE, overwrite = TRUE)

excel_data <- read_excel("data/airports.xlsx")
dbWriteTable(mydb, "airports", excel_data, row.names = FALSE, overwrite = TRUE)

flights_data <- read_excel("data/flights.xlsx")
dbWriteTable(mydb, "flights", flights_data, row.names = FALSE, overwrite = TRUE)

text <- pdf_text("data/weather.pdf")
lines <- str_split(text, "\n")[[1]]
data_list <- str_split(lines, ",") 
weather <- as.data.frame(do.call(rbind, data_list[-1]))
colnames(weather) <- c("origin","year","month","day","hour","temp","dewp","humid","wind_dir","wind_speed","wind_gust","precip","pressure","visib","time_hour")
dbWriteTable(mydb, "weather", weather, row.names = FALSE, overwrite = TRUE)

dbDisconnect(mydb)
```


```{r}
library(readxl)
airports <- read_excel("data/airports.xlsx")

library(jsonlite)
airlines <- jsonlite::fromJSON("data/airlines.json")
```

# Mission 1
## 1.
```{r}
# Compter le nombre d'aéroports

result <- dbGetQuery(mydb, "SELECT COUNT(*) AS nbr_airports FROM airports")
print(result)
```

```{r}
# Nombre d'aéroprt qui ne changent pas de fuseaux horaires

result <- dbGetQuery(mydb, "SELECT dst, COUNT(*) FROM airports GROUP BY dst")
print(result)
```

```{r}
# Nombre de fuseaux horaires différents
result <- dbGetQuery(mydb, "SELECT COUNT(DISTINCT(tzone)) FROM airports")
print(result)
```

```{r}
# Nombre de companies
result <- dbGetQuery(mydb, "SELECT COUNT(*) AS nbr_companies FROM airlines")
print(result)
```

```{r}
# Nombre d'avions

result <- dbGetQuery(mydb, "SELECT COUNT(*) AS nbr_avions FROM planes")
print(result)
```

```{r}
# Nombre de vols annulés

result <- dbGetQuery(mydb, "SELECT COUNT(*) FROM flights WHERE air_time IS NULL")
print(result)
```

## 2
```{r}
# aéroport de départ le plus emprunté

result <- dbGetQuery(mydb, "SELECT a.name, COUNT(*) AS depart 
FROM flights f 
LEFT JOIN airports a ON f.origin = a.faa 
GROUP BY f.origin  
ORDER BY depart DESC 
LIMIT 1;")
print(result)
```

```{r}
# destination les plus prisés

result <- dbGetQuery(mydb, "SELECT a.name, COUNT(*) AS destination, (COUNT(*) / (SELECT COUNT(*) FROM flights) * 100) AS pourcentage
FROM flights f 
LEFT JOIN airports a ON f.dest = a.faa 
GROUP BY dest  
ORDER BY destination DESC;")
print(result)
```

```{r}
# destination les moins prisés

result <- dbGetQuery(mydb, "SELECT a.name, COUNT(*) AS destination, (COUNT(*) / (SELECT COUNT(*) FROM flights) * 100) AS percent
FROM flights f 
LEFT JOIN airports a ON f.dest = a.faa 
GROUP BY dest  
ORDER BY destination ASC;")
print(result)
```

```{r}
# les 10 avions qui ont le plus décollés

result <- dbGetQuery(mydb, "SELECT tailnum, COUNT(*) AS count
FROM flights 
WHERE tailnum IS NOT NULL
GROUP BY tailnum
ORDER BY count DESC
LIMIT 10;")
print(result)
```

```{r}
# les 10 avions qui ont le moins décollés

result <- dbGetQuery(mydb, "SELECT tailnum, COUNT(*) AS count
FROM flights 
WHERE tailnum IS NOT NULL
GROUP BY tailnum
ORDER BY count ASC
LIMIT 10;")
print(result)
```
## 3

```{r}
# nombre de de destination par companie

result <- dbGetQuery(mydb, "SELECT carrier, COUNT(DISTINCT dest) AS count
FROM flights 
GROUP BY carrier;")
print(result)
```

```{r}
# nombre de de destination par companie

result <- dbGetQuery(mydb, "SELECT carrier, COUNT(DISTINCT dest) AS count
FROM flights 
GROUP BY carrier;")
print(result)
```

## 4
Les vols ayant attéri à Houston

```{r}
df <- dbGetQuery(mydb, "SELECT * FROM flights;")
filtered_df <- subset(df, dest %in% c("IAH", "HOU"))
print(filtered_df)
```

le nombre de vol partant de NYC vers Seattle (dans ce dataset, tous les vols partent de NYC)
```{r}
filtered_df <- nrow(subset(df, dest == "SEA"))
print(filtered_df)
```
Les companies qui deservent Seattle
```{r}
filtered_df <- unique(subset(df, dest == "SEA")$carrier)
print(filtered_df)
```

Le nombre d'avion unique qui vont à Seattle
```{r}
filtered_df <- length(unique(subset(df, dest == "SEA")$tailnum))
print(filtered_df)
```

## 5
```{r}
# Question 5
flights <- dbGetQuery(mydb, "SELECT *, origin AS flight_origin FROM `flights`")
airports <- dbGetQuery(mydb, "SELECT * FROM `airports`")
View(flights)
View(airports)
sapply(flights, class)

# 1. Nombre de vols par destination
library(dplyr)

flights_by_dest = flights %>% 
  group_by(dest) %>% 
  summarise(n_flights = n())

View(flights_by_dest)

# flights_by_dest_with_name = rename(flights_by_dest, origin_name = origin)

flights_by_dest_with_name <- flights_by_dest %>%
  left_join(airports, by = c("dest" = "faa")) %>%
  select(dest, name, n_flights) %>%
  rename(destination_name = name)

colnames(flights)

View(flights_by_dest_with_name)

# 2. 
flight_by_dest_origin <- flights %>%
  left_join(airports, by = c("dest" = "faa")) %>%
  select(dest, name, flight_origin, carrier) %>%
  rename(destination_airport = name)
View(flight_by_dest_origin)

flight_by_dest_origin <- flights %>%
  left_join(airports, by = c("dest" = "faa")) %>%
  rename(destination_airport = name) %>%
  left_join(airports, by = c("flight_origin" = "faa")) %>%
  rename(origin_airport = name) %>%
  select(destination_airport, origin_airport, carrier, time_hour) %>%
  arrange(destination_airport, origin_airport, carrier)


View(flight_by_dest_origin)
```


## 7
Les destination exclussives aux companies
```{r}
filtered_df <- df %>%
  group_by(dest) %>%
  filter(n_distinct(carrier) == 1) %>%
  summarise(carrier = first(carrier))
print(filtered_df)
```

